# Site settings
title: Alex Hanson
email: ahanson@runbox.com
description: > # this means to ignore newlines until "baseurl:"
  Here's my personal portfolio site. It sure needs a lot of work.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: j_narwhal
github_username:  ahanson

# Build settings
markdown: kramdown
gems:
- jekyll-compass
